---
- name: Ensure required packages are present
  ansible.builtin.apt:
    name:
      - gpg
      - apt-transport-https
      - python3-debian  # required by deb822_repository on the target
    state: present

- name: Add kernel.org Ubuntu mirror (main, updates, backports)
  ansible.builtin.deb822_repository:
    name: kernel-org-ubuntu
    types: [ deb, deb-src ]
    uris:
      - "https://mirrors.kernel.org/ubuntu"
    suites:
      - "{{ ansible_distribution_release }}"
      - "{{ ansible_distribution_release }}-updates"
      - "{{ ansible_distribution_release }}-backports"
    components:
      - main
      - restricted
      - universe
      - multiverse
    signed_by: /usr/share/keyrings/ubuntu-archive-keyring.gpg
    state: present
    enabled: yes
  notify: Update APT cache
